---
- name: Render systemd-wide configuration
  become: true
  template:
    src: "{{ tmux_config_file }}.j2"
    dest: "{{ global_config_dir }}/{{ tmux_config_file }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  vars:
    account: global
  when: tmux_config is defined and "global" in tmux_config

- name: Render user configuration
  become: true
  template:
    src: "{{ tmux_config_file }}.j2"
    dest: "/home/{{ item }}/.{{ tmux_config_file }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
    backup: true
  vars:
    account: "{{ item }}"
  with_items: "{{ tmux_config.keys() | difference(['global']) }}"
  when: tmux_config is defined and tmux_config.keys() | difference(['global']) | length > 0
