---
- name: Render systemd-wide configuration
  become: true
  template:
    src: "{{ _tmux_config_file }}.j2"
    dest: "{{ _global_config_dir }}/{{ _tmux_config_file }}"
    owner: root
    group: root
    mode: 0644
    backup: true
  vars:
    account: global
  when: tmux_config is not none and "global" in tmux_config
  tags:
    - config
    - global

- name: Render user configuration
  become: true
  template:
    src: "{{ _tmux_config_file }}.j2"
    dest: "/home/{{ item }}/.{{ _tmux_config_file }}"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0644
    backup: true
  vars:
    account: "{{ item }}"
  with_items: "{{ tmux_config.keys() | difference(['global']) }}"
  when: tmux_config is not none and tmux_config.keys() | difference(['global']) | length > 0
  tags:
    - config
    - user
