---
- name: Check for uninstall signal
  when: perform_uninstall
  block:
    - name: Broadcast uninstall signal
      command: /bin/true
      notify: Uninstall service
      when: perform_uninstall

    - name: End play following uninstallation
      meta: end_play
